version = 1

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/brunolimame/bolao"

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "docker"
enabled = true

  [analyzers.meta]
  dockerfile_paths = [
    ".docker/Dockerfile",
    ".docker/Dockerfile.prod",
  ]

  trusted_registries = [
    "docker.io"
  ]