# skipcq: DOK-DL3007
FROM golang:latest as builder
WORKDIR /app
COPY . . 
RUN GOOS=linux CGO_ENABLE=0 go build -ldflags="-w -s" -o bolao-server .

FROM scratch
WORKDIR /app
COPY --from=builder /app/bolao-server .
CMD ["./bolao-server"]